### ISSUE TITLE
Only Audio an Raspberry pi, No video on mirror

### ISSUE THREAD

**Issue by matze6486** [kevinatown/MMM-Screencast#100]
Hey!

I've got a problem with the screencast module.

Configuartions:  
Internet via HotSpot from Iphone 8:  PI & Iphone 11 (streaming device)
Bluetooth Iphone (11) <--> Pi,    

First: On MM I only can see my background-wallpaper.
When I start Youtube on the IPhone 11 and want to cast a video via "AirPlay & bluetooth" devices, it shows the PI and if I select the Pi it only plays the audio on the PI, but not the video on the mirror.

config of the module is copied from your example
logfile is attached.

I hope you can help me with that problem. 
Matze

Here is my logfile (sorry, but the editor "doesnt support a textfile")....

magicmirror@2.14.0 start /home/pi/MagicMirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

....

[14.01.2021 22:32.11.673] [LOG]   Module helper loaded: MMM-Screencast
[14.01.2021 22:32.11.676] [LOG]   All module helpers loaded.
[14.01.2021 22:32.11.849] [LOG]   Starting server on port 8080 ... 
[14.01.2021 22:32.11.876] [LOG]   Server started ...

....

[14.01.2021 22:32.11.882] [LOG]   Connecting socket for: MMM-Screencast
[14.01.2021 22:32.11.883] [LOG]   Sockets connected & modules started ...
[14.01.2021 22:32.12.276] [LOG]   Launching application.
[14.01.2021 22:32.12.342] [WARN]  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[14.01.2021 22:32.16.215] [ERROR] Whoops! There was an uncaught exception...
[14.01.2021 22:32.16.242] [ERROR] Error: Cannot find module '../../build/Release/ioctls'

....

- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-KeyBindings/node_modules/evdev/lib/Device/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
....
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[14.01.2021 22:32.16.248] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[14.01.2021 22:32.16.249] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
....
[14.01.2021 22:32.16.324] [INFO]  Checking git for module: MMM-Screencast
[14.01.2021 22:33.33.121] [ERROR] (node:30317) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by kevinatown** [comment]
Hey @matze6486! Sorry to see that you are having issues. Is it possible to paste the entire log file in here? It'll make it a lot easier to determine what is happening. You can get this by running:

```bash
display=:0 npm start >> log.log
```

Allowing the MM to start up, wait for a few, and then paste the entire `log.log` in this chat. 

Also have to ask, did you install all of the dependencies in MMM-Screencast?

**Comment by matze6486** [comment]
thx for reply
I deleted the module but i‘ll try tomorrow again.

**Comment by matze6486** [comment]
Not ist works, but its on a different sd-Card. So i have a another configuration.
