### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by JustinTomerlin** [kevinatown/MMM-Screencast#131]
I've added the module and add the config code in the config file.
I tried launching the magic mirror and it worked it showed up under the devices but when I clicked on the screen to play the video it just says "connecting..." for a few mins and then times out. but when it times out and I try to connect to the device the device is no longer there until I restart magic mirror.

Any help would be greatly appreciated.

**Comment by Egnos87** [comment]
Similar problem for me too: it often happens that it is no longer possible to reconnect after a disconnection.
It also happens when, after the disconnecting, you try to reconnect with a new user.
Below is the message that appears on the MM terminal when it is no longer possible to connect:

```
[30.09.2022 20:48.26.469] [LOG]   screencast stdout: 
> magicmirror-screencast@0.0.5 start
> electron app.js

```

Please @kevinatown help us!

Thanks.

**Comment by kevinatown** [comment]
@Egnos87 @JustinTomerlin could y’all send me the entire boot up log? A copy of your config with any API keys removed? Also what model of pi are you running it on?

**Comment by peternguy3n** [comment]
@kevinatown @JustinTomerlin @Egnos87 First time setting up Magic Mirror and I resolved all my issues by basing my build off of the Raspberry Pi Buster image. Spent too much time trying to make Bullseye work. Loaded Buster and all is working well out the box.

**Comment by Egnos87** [comment]
Hi @kevinatown the problem has happened again.
Now I try to start the MM with `npm start >> log.log` and when it happens again I will send you the log.

Please @kevinatown  don't let this beautiful module die! ;-)

Thank you.

**Comment by Tom-Hirschberger** [comment]
Hi,

cause of @Egnos87 i tried installing the module. It looks like the problem only exists with Raspberry OS Buster but not with Bullseye.

First i need to say that i use the Branch of [smartgic](https://github.com/smartgic/MMM-Screencast/tree/fix_window_still_visible) which fixes the not closing window of ticket #128 

On Buster the connection fails and the log shows the following error
```text
> electron app.js


[06.11.2022 14:32.30.345] [LOG]   screencast stderr: [20584:1106/143230.345216:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.

[06.11.2022 14:32.30.350] [LOG]   screencast stderr: /home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron/dist/electron exited with signal SIGTRAP
```

I followed the suggestions with:
```bash
cd ~/MagicMirror/modules/MMM-Screencast/node_modules/electron/dist
sudo chown root:root chrome-sandbox 
sudo chmod 4755 chrome-sandbox
```

And after this everything works well.

**Comment by Tom-Hirschberger** [comment]
On Bullseye i get the following warning
```text
> magicmirror-screencast@0.0.5 start
> electron app.js


[05.11.2022 17:41.26.364] [LOG]   screencast stderr: (node:3143) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```
but everything works well

**Comment by Tom-Hirschberger** [comment]
Played a little bit with two clients connecting to the Buster instance today.
* I connected client one, played a video and disconnected it. The video plays as expected and the window closes (i still use the fixed branch)
* I connected client two, played a video and disconnected it. Everything works well.
* I repeated connecting, playing and disconnecting several times and suddenly no connection was possible anymore.

The log shows the following error in this moment:

```text
[07.11.2022 08:29.12.416] [ERROR] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (/home/pi/MagicMirror/node_modules/express/lib/response.js:794:10)
    at ServerResponse.contentType (/home/pi/MagicMirror/node_modules/express/lib/response.js:624:15)
    at ServerResponse.sendStatus (/home/pi/MagicMirror/node_modules/express/lib/response.js:373:8)
    at /home/pi/MagicMirror/modules/MMM-Screencast/node_modules/peer-dial/lib/peer-dial.js:110:25
    at /home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:85:15
    at Client.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/ipc.js:70:36)
    at Client.emit (/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/event-pubsub/es5.js:74:21)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/node-ipc/dao/client.js:241:24) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by Wdave40** [comment]
I am having the same issue, the endless spinner. Below are my logs from PM2 and my OS info. 
![Screenshot 2022-11-21 at 10 45 29 AM](https://user-images.githubusercontent.com/76792845/203125095-34f6a3cd-1352-4b3c-ac33-2205e72fc18f.png)
![Screenshot 2022-11-21 at 10 46 35 AM](https://user-images.githubusercontent.com/76792845/203125106-54bb77ad-d925-41c7-86d7-664860d46f22.png)
