### ISSUE TITLE
Javascript Exception when starting stream. 

### ISSUE THREAD

**Issue by hannes2323** [kevinatown/MMM-Screencast#21]
Hi,

first of all, thank you for your great work!

I run MM on raspberry pi 3 b+. MMM-Screencast installed fine and my phone finds the casting service. But when i click on "stream to <hostname>", i get following exception:

```
$ DISPLAY=:0 npm start                                                                                                                          

> magicmirror@2.5.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.5.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Screencast
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: MMM-Screencast
Sockets connected & modules started ...
Launching application.
DIAL Server is running on PORT 8569
Whoops! There was an uncaught exception...
{ Error: spawn npm ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs:
   [ 'start',
     'http://www.youtube.com/tv?pairingCode=c4a965d2-f603-47d9-9d4a-7abd03e33e9e&theme=cl&rUrl=ws%3A%2F%2F192.168.0.130%3A39588%2Fd661c4c2-a2ab-48f2-ba9a-49622a161be5&rId=ta69c0aavsnut1s497h7mpa2vp&launch=dial-watch',
     'bottomRight',
     500,
     300 ] }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues`
```
MM was startet with a minimal config, only Screencast as module included:

```
`/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
        address: "localhost", // Address to listen on, can be:
                              // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                              // - another specific IPv4/6 to listen on a specific interface
                              // - "", "0.0.0.0", "::" to listen on any interface
                              // Default, when address config is left out, is "localhost"
        port: 8080,
        ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
                                                               // or add a specific IPv4 of 192.168.1.5 :
                                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
                                                               // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
                                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

        language: "de",
        timeFormat: 24,
        units: "metric",

        modules: [
                {
                        module: '3rd_party/MMM-Screencast',
                        position: 'bottom_right', // This position is for a hidden <div /> and not the screencast window
                        config: {
                                position: 'bottomRight',
                                height: 300,
                                width: 500,
                        }
                },
        ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}`
```

I saw another issue on github with the same error, but no solution. Could you please assist?

Thank you!

**Comment by kevinatown** [comment]
This is a little tricky. It looks like there is an issue with cross-spawn. Some quick questions:
- what node version are you on?
- what npm version?

**Comment by hannes2323** [comment]
Thank you for your reply.

- Node version is : v9.11.2
- npm is : 6.4.1
- Yes, I am running on raspbian.

Is there anything else I can provide or help with?

Thanks for your time!

**Comment by kevinatown** [comment]
Hey @hannes2323, this was helpful, but unfortunately did not point me to the solution. The issue is that `spawn` can't find the command `npm` not sure why. Let me think about this.

**Comment by hannes2323** [comment]
Shame  on me, great point: I put your module in "modules/3rd_party/" to distinguish between stock on other modules. After putting the module directly in "modules" it worked like a charm!

Sorry for all the trouble caused by me and thanks for your help!

This issue can be closed.

**Comment by kevinatown** [comment]
Awesome! Glad you got it working. If you'd like to keep it in the `modules/3rd_party/` dir you can move it back and change line 28 in `MMM-Screencast/DialServer.js` from:

```
cwd: 'modules/MMM-Screencast'
```

to:
```
cwd: 'modules/3rd_party/MMM-Screencast'
```

Good luck and enjoy!
