### ISSUE TITLE
Java Issue

### ISSUE THREAD

**Issue by KutscheMa** [kevinatown/MMM-Screencast#34]
Hey Kevin,

this is my issue:

Uncaught Exception:
TypeError: Cannot read property 'x' of undefined
    at Positioner.move (/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron-positioner/index.js:113:44)
    at App.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/app.js:41:14)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

Can you help me?

**Comment by kevinatown** [comment]
Hey @KutscheMa! It looks like you didn't provide a position for the youtube window in the config. Can you paste an example of your config?

Also you can see the config example here: https://github.com/kevinatown/MMM-Screencast/blob/master/README.md

**Comment by KutscheMa** [comment]
Hi Kevin,

i have fixed it. It was the position. Thank you.
