### ISSUE TITLE
error loading See attached log

### ISSUE THREAD

**Issue by rothestar** [kevinatown/MMM-Screencast#39]

**Comment by rothestar** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   'http://www.youtube.com/tv?pairingCode=FC23707C-CDE7-4C43-AE00-BEC3D5BB2468&theme=cl&dialLaunch=watch',
1 verbose cli   'bottomRight',
1 verbose cli   '500',
1 verbose cli   '300' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror-screencast@0.0.3~prestart: magicmirror-screencast@0.0.3
6 info lifecycle magicmirror-screencast@0.0.3~start: magicmirror-screencast@0.0.3
7 verbose lifecycle magicmirror-screencast@0.0.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror-screencast@0.0.3~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle magicmirror-screencast@0.0.3~start: CWD: /home/pi/MagicMirror/modules/MMM-Screencast
10 silly lifecycle magicmirror-screencast@0.0.3~start: Args: [ '-c',
10 silly lifecycle   'electron app.js "http://www.youtube.com/tv?pairingCode=FC23707C-CDE7-4C43-AE00-BEC3D5BB2468&theme=cl&dialLaunch=watch" "bottomRight" "500" "300"' ]
11 info lifecycle magicmirror-screencast@0.0.3~start: Failed to exec start script
12 verbose stack Error: magicmirror-screencast@0.0.3 start: `electron app.js "http://www.youtube.com/tv?pairingCode=FC23707C-CDE7-4C43-AE00-BEC3D5BB2468&theme=cl&dialLaunch=watch" "bottomRight" "500" "300"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid magicmirror-screencast@0.0.3
14 verbose cwd /home/pi/MagicMirror/modules/MMM-Screencast
15 verbose Linux 4.19.57-v7+
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "http://www.youtube.com/tv?pairingCode=FC23707C-CDE7-4C43-AE00-BEC3D5BB2468&theme=cl&dialLaunch=watch" "bottomRight" "500" "300"
17 verbose node v10.16.3
18 verbose npm  v6.9.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error magicmirror-screencast@0.0.3 start: `electron app.js "http://www.youtube.com/tv?pairingCode=FC23707C-CDE7-4C43-AE00-BEC3D5BB2468&theme=cl&dialLaunch=watch" "bottomRight" "500" "300"`
23 error spawn ENOENT
24 error Failed at the magicmirror-screencast@0.0.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by georgebalt** [comment]
I run into a similar error and log being generated when attempting to cast a video. Fresh Magic Mirror and MMM-Screencast install.

**Comment by kevinatown** [comment]
Hey @georgebalt and @rothestar this is very odd it looks like there is an issue launching electron within MMM-Screencast. Did you follow the instructions and install all of MMM-Screencast's dependencies? Also I updated some of the packages, so you might want to pull the most recent version of MMM-Screencast.
