### ISSUE TITLE
Error // If I run it, I will get an error.

### ISSUE THREAD

**Issue by dnwnd16561** [kevinatown/MMM-Screencast#43]
When I run a smart mirror and connect to YouTube, I encounter errors.
Here's what it says.

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'x' of undefined
  at Positioner.move(/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron-positioner/index.js:113:45)
at App.<anonymous>(/home/pi/MagicMirror/modules/MMM-Screencast/app.js:50:14)
 at Object.onceWrapper(events.js:273:13)
 at App.emit (events.js:187:15)

Please help me

**Comment by kevinatown** [comment]
Hey @dnwnd16561 this looks like a config issue. Can you paste your config.js in here (with all of the api keys removed). Thanks!

**Comment by pandora0309** [comment]
This problem has been solved. But I'm connected to the same Wi-Fi, but I can't connect the raspberry pie to YouTube.

**Comment by kevinatown** [comment]
@pandora0309 this seems to be off topic for this issue. Can you please open a new issue with the logs of you starting up the app, trying to connect, and then closing the app. 

Thanks!

**Comment by pandora0309** [comment]
Thankfully, I've been able to correct the error. Thank you for your help!! Thank you for creating these programs.

**Comment by UltSurv** [comment]
Where has this been fixed? I'm having the same problem.

**Comment by IngveBoe** [comment]
> This problem has been solved. But I'm connected to the same Wi-Fi, but I can't connect the raspberry pie to YouTube.

how did you fix it? i have the same problem [Screenshot link imgur](https://imgur.com/o4azY3f)

**Comment by kevinatown** [comment]
Closing this issues as the original issue was solved.

@IngveBoe this is a config issue, you most likely used the positioning args for MM and not MMM-Screencast. You can double check this on the [readme](https://github.com/kevinatown/MMM-Screencast/blob/master/README.md) 

Also if you are still having issues, can you please open a new issue with a copy of your config (with  all api keys removed/redacted). Thanks!!
