### ISSUE TITLE
Screencast not Starting up. (Error Log in post) 

### ISSUE THREAD

**Issue by derartlars** [kevinatown/MMM-Screencast#62]
Hi MMM-Screencast was correctly installed but is not starting. 

When I insert: display=:0 npm start >> log.log I get the following message: 

(electron:1097): Gtk-WARNING **: 14:17:33.868: cannot open display: 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror-screencast@0.0.5 start: `electron app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the magicmirror-screencast@0.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-04-02T12_17_33_958Z-debug.log

Following up is the debug log: 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror-screencast@0.0.5~prestart: magicmirror-screencast@0.0.5
6 info lifecycle magicmirror-screencast@0.0.5~start: magicmirror-screencast@0.0.5
7 verbose lifecycle magicmirror-screencast@0.0.5~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror-screencast@0.0.5~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/modules/MMM-Screencast/node_modules/.bin:/home/pi/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle magicmirror-screencast@0.0.5~start: CWD: /home/pi/MagicMirror/modules/MMM-Screencast
10 silly lifecycle magicmirror-screencast@0.0.5~start: Args: [ '-c', 'electron app.js' ]
11 silly lifecycle magicmirror-screencast@0.0.5~start: Returned: code: 1  signal: null
12 info lifecycle magicmirror-screencast@0.0.5~start: Failed to exec start script
13 verbose stack Error: magicmirror-screencast@0.0.5 start: `electron app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid magicmirror-screencast@0.0.5
15 verbose cwd /home/pi/MagicMirror/modules/MMM-Screencast
16 verbose Linux 4.19.97-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error magicmirror-screencast@0.0.5 start: `electron app.js`
22 error Exit status 1
23 error Failed at the magicmirror-screencast@0.0.5 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kevinatown** [comment]
Hi @derartlars! Sorry for the late reply, I've been slammed with work and avoiding everything else.  

So it looks as if you're running `npm start` from the `MMM-Screencast` directory? Is this true? If so can you run the same command from the Magic Mirror root directory and send the log here?
