### ISSUE TITLE
Electron Error

### ISSUE THREAD

**Issue by uok825** [kevinatown/MMM-Screencast#82]
````
 screencast stdout:
0|MagicMirror  | > magicmirror-screencast@0.0.5 start /home/pi/MagicMirror/modul                                                                                                             es/MMM-Screencast
0|MagicMirror  | > electron app.js
0|MagicMirror  | [2020-08-09 21:44:17.889] [LOG]
0|MagicMirror  | screencast stderr: /home/pi/MagicMirror/node_modules/electron/i                                                                                                             ndex.js:14
0|MagicMirror  |     throw new Error('Electron failed to install correctly, plea                                                                                                             se delete node_modules/electron and try installing again')
0|MagicMirror  |     ^
0|MagicMirror  | Error: Electron failed to install correctly, please delete node                                                                                                             _modules/electron and try installing again
0|MagicMirror  |     at getElectronPath (/home/pi/MagicMirror/node_modules/elect                                                                                                             ron/index.js:14:11)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/node_modules/el                                                                                                             ectron/index.js:18:18)
0|MagicMirror  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|MagicMirror  |     at Object.Module._extensions..js (internal/modules/cjs/load                                                                                                             er.js:789:10)
0|MagicMirror  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|MagicMirror  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|MagicMirror  |     at Function.Module._load (internal/modules/cjs/loader.js:58                                                                                                             5:3)
0|MagicMirror  |     at Module.require (internal/modules/cjs/loader.js:692:17)
0|MagicMirror  |     at require (internal/modules/cjs/helpers.js:25:18)
0|MagicMirror  |     at Object.<anonymous> (/home/pi/MagicMirror/node_modules/el                                                                                                             ectron/cli.js:3:16)
0|MagicMirror  | [2020-08-09 21:44:18.040] [LOG]
0|MagicMirror  | screencast stderr: npm
0|MagicMirror  | [2020-08-09 21:44:18.086] [LOG]
0|MagicMirror  | screencast stderr:  ERR! code ELIFECYCLE
0|MagicMirror  | [2020-08-09 21:44:18.138] [LOG]
0|MagicMirror  | screencast stderr: npm ERR! errno
0|MagicMirror  | [2020-08-09 21:44:18.195] [LOG]
0|MagicMirror  | screencast stderr:  1
0|MagicMirror  | [2020-08-09 21:44:18.281] [LOG]
0|MagicMirror  | screencast stderr: npm
0|MagicMirror  | [2020-08-09 21:44:18.331] [LOG]
0|MagicMirror  | screencast stderr:
0|MagicMirror  | [2020-08-09 21:44:18.398] [LOG]
0|MagicMirror  | screencast stderr: ERR! magicmirror-screencast@0.0.5 start: `el                                                                                                             ectron app.js`
0|MagicMirror  | npm ERR! Exit status 1
0|MagicMirror  | npm
0|MagicMirror  | [2020-08-09 21:44:18.452] [LOG]
0|MagicMirror  | screencast stderr: ERR!
0|MagicMirror  | npm ERR! Failed at the magicmirror-screencast@0.0.5 start scrip                                                                                                             t.
0|MagicMirror  | npm ERR!
0|MagicMirror  | [2020-08-09 21:44:18.523] [LOG]
0|MagicMirror  | screencast stderr:  This is probably not a problem with npm. Th                                                                                                             ere is likely additional logging output above.
0|MagicMirror  | [2020-08-09 21:44:18.674] [LOG]
0|MagicMirror  | screencast stderr:
0|MagicMirror  | [2020-08-09 21:44:18.699] [LOG]    screencast stderr: npm
0|MagicMirror  | [2020-08-09 21:44:18.709] [LOG]
0|MagicMirror  | screencast stderr:  ERR! A complete log of this run can be foun                                                                                                             d in:
0|MagicMirror  | npm ERR!
0|MagicMirror  | [2020-08-09 21:44:18.780] [LOG]
0|MagicMirror  | screencast stderr:      /home/pi/.npm/_logs/2020-08-09T18_44_18                                                                                                             _627Z-debug.log
0|MagicMirror  | [2020-08-09 21:44:18.905] [LOG]
0|MagicMirror  | closing code: 1
````

**Comment by kevinatown** [comment]
Hi @uok825 what version of node are you using? Also you can try to bump up the electron version to see if it helps (I will try and do this in the module soon).

**Comment by uok825** [comment]
I use pi zero and i dont know node version right now
