### ISSUE TITLE
Could not find module 'peer-dial'

### ISSUE THREAD

**Issue by mollyschilling** [kevinatown/MMM-Screencast#84]
I installed everything, but when i go to start up my mirror, none of the modules show up. I went back to review the code and it says that it cannot fine a module called peer-dial. Could anyone help me troubleshoot? Also does screen casting work with apple?

My code when trying to run:

[2020-08-20 10:24:30.782] [LOG]    Module helper loaded: MMM-AlexaControl
[2020-08-20 10:24:30.794] [ERROR]  WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'peer-dial'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js
- /home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[2020-08-20 10:24:30.797] [LOG]    Loading module helpers ...
[2020-08-20 10:24:30.800] [LOG]    No helper found for module: alert.
[2020-08-20 10:24:30.802] [LOG]    No helper found for module: MMM-GooglePhotos.
[2020-08-20 10:24:30.804] [LOG]    Initializing new module helper ...
[2020-08-20 10:24:30.805] [LOG]    Module helper loaded: MMM-AlexaControl
[2020-08-20 10:24:30.809] [ERROR]  App threw an error during load
[2020-08-20 10:24:30.811] [ERROR]  Error: Cannot find module 'peer-dial'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js
- /home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
[2020-08-20 10:24:30.814] [ERROR]  Whoops! There was an uncaught exception...
[2020-08-20 10:24:30.815] [ERROR]  Error: Cannot find module 'peer-dial'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js
- /home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Screencast/DialServer.js',
    '/home/pi/MagicMirror/modules/MMM-Screencast/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[2020-08-20 10:24:30.844] [ERROR]  MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2020-08-20 10:24:30.845] [ERROR]  If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by kevinatown** [comment]
Hi @mollyschilling! 

Sorry to hear that you are having issues. I have a few questions to better help diagnose your issue:
1. Did you install MMM-Screencast's dependencies? The directions should be on the readme, but pretty much you `cd` into `MMM-Screencast`'s dir and run `npm install` there. (This is honestly what I think is wrong)
2. Can you attach to this issue a copy of your config.js (with all API key's removed)? This could help with this issue: ` Could not load config file`

Thanks! And good luck!!

**Comment by cluelesscarter** [comment]
Hey @kevinatown,

I recently tried to install and received the following errors; I tried running `npm audit fix` but it didn't work, is this related to this issue or do I need to open a new one? I can't see the pi on my devices list....

```
pi@raspberrypi:~/MagicMirror/modules/MMM-Screencast $ npm install
npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> electron@3.1.13 postinstall /home/pi/MagicMirror/modules/MMM-Screencast/node_modules/electron
> node install.js

Downloading tmp-15439-1-SHASUMS256.txt-3.1.13
[============================================>] 100.0% of 4.79 kB (4.79 kB/s)
npm notice created a lockfile as package-lock.json. You should commit this file.
added 207 packages from 211 contributors and audited 207 packages in 52.548s

4 packages are looking for funding
  run `npm fund` for details

found 12 vulnerabilities (5 low, 2 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/MagicMirror/modules/MMM-Screencast $ npm audit fix
up to date in 5.152s

4 packages are looking for funding
  run `npm fund` for details

fixed 0 of 12 vulnerabilities in 207 scanned packages
  12 vulnerabilities required manual review and could not be updated
pi@raspberrypi:~/MagicMirror/modules/MMM-Screencast $ 

```

**Comment by DiDavid** [comment]
Hi @kevinatown,
I have the same problem, but I can't do "npm install", then i got this error:

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/node-uuid: Integrity verification failed for sha512-sDjbdVLgpPrsMHC3QV3yM3tD4Q1lcHfoPgEDdvl4YJwiqvuA9FB8Q0mij4NCuBdTKf2luL6pcKGqVwibKIEV6g== (/home/pi/.npm/_cacache/content-v2/sha512/b0/38/db7552e0a4faec3070b7415df2337b43e10d657077e83e010376f978609c22aafb80f4507c4349a28f8342b8175329fda5b8bea970a1aa57089b288115ea)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-09-27T15_44_09_918Z-debug.log

I hope you can help me.
